name: Naukri Profile Update (Playwright)

on:
  schedule:
    - cron: '30 0-6 * * *'  # Every hour from 6 AM to 12 PM IST
  workflow_dispatch:

jobs:
  update-profile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install playwright
          playwright install

      - name: Run Naukri updater
        run: |
          python naukri_playwright.py
