name: Naukri Profile Updater

on:
  schedule:
    - cron: '30 0-6 * * *'
  workflow_dispatch:

jobs:
  update-profile:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb
        pip install -r requirements.txt

    - name: Install Chrome
      run: |
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install -y ./google-chrome-stable_current_amd64.deb

    - name: Start virtual display
      run: |
        Xvfb :99 -screen 0 1920x1080x24 &
        export DISPLAY=:99

    - name: Run Naukri updater
      run: |
        export DISPLAY=:99
        python naukri.py
