name: Naukri Profile Update (Playwright)

on:
  workflow_dispatch:

jobs:
  update-profile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Unzip Naukri profile
        run: |
          if [ -f naukri_profile.zip ]; then
            echo "Unzipping profile..."
            unzip naukri_profile.zip -d naukri_profile
          else
            echo "❌ naukri_profile.zip not found!"
            exit 1
          fi

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install playwright
          playwright install

      - name: Run Naukri updater
        run: python naukri_playwright.py

      - name: Re-zip updated profile
        run: zip -r naukri_profile.zip naukri_profile/
