name: Naukri Profile Update (Playwright)

on:
  schedule:
    - cron: "30 0-6 * * *" # Every hour from 6 AM to 12 PM IST
  workflow_dispatch:

jobs:
  update-profile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Upload session if present
        run: |
          if [ -f naukri_profile.zip ]; then
            echo "Session zip found. Uploading..."
            gh release create temp-session naukri_profile.zip --repo ${{ github.repository }}
          else
            echo "No session zip found. Skipping upload."
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download session (if exists)
        uses: actions/download-artifact@v4
        with:
          name: naukri_profile
          path: naukri_profile
        continue-on-error: true

      - name: Unzip session
        run: |
          if [ -f naukri_profile/naukri_profile.zip ]; then
            unzip naukri_profile/naukri_profile.zip -d naukri_profile
          else
            echo "No session zip to unzip."
          fi

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install playwright
          playwright install

      - name: Run Naukri updater
        run: python naukri_playwright.py

      - name: Re-zip updated session
        run: zip -r naukri_profile.zip naukri_profile/

      - name: Upload updated session
        uses: actions/upload-artifact@v4
        with:
          name: naukri_profile
          path: naukri_profile.zip
          retention-days: 30
